.\" Manpage for dasom-daemon.
.\" Contact Hodong Kim <hodong@cogno.org>.
.TH dasom-daemon 1 "January 2016" "1.3" "dasom-daemon man page"
.SH NAME
dasom-daemon \- Input Method Framework
.SH DESCRIPTION
Dasom is an input method framework, which provides
.PP
•Input Method Server
.TP
.PP
◦dasom-daemon including XIM
.PP
•Indicators
.TP
.PP
◦GNOME shell: dasom agent extension
.TP
.PP
◦KDE, Unity, GNOME panel: dasom-indicator (based on libappindicator3)
.SH SYNOPSIS
Usage:
.TP
.PP
dasom-daemon [OPTION...] - Dasom Input Method Daemon
.SH OPTIONS
Help Options:
.TP
.PP
-h, --help
Show help options
.PP
Application Options:
.TP
.PP
--no-daemon
Do not daemonize
.TP
.PP
--debug
Log debugging message
.TP
.PP
--version        
Version
.PP
.SH AUTHOR
Maintainer: Hodong Kim <hodong@cogno.org>
